export const staticFiles = {
  icons: {
    cart: "/assets/icons/cart.svg",
    lock: "/assets/icons/lock.svg",
    profile: "/assets/icons/profile.svg",
    sign_up: "/assets/icons/sign_up.svg",
    facebook: "/assets/icons/facebook.svg",
    instagram: "/assets/icons/instagram.svg",
    blog: "/assets/icons/blog.svg",
    google: "/assets/icons/google.svg",
    naver: "/assets/icons/naver.svg",
    messages_bubble: "/assets/icons/messages_bubble.svg",
    shopping_bag: "/assets/icons/shopping_bag.svg",
    dollar_circle: "/assets/icons/dollar_circle.svg",
    call: "/assets/icons/call.svg",
    thumbs_up: "/assets/icons/thumbs_up.svg",
    coffee: "/assets/icons/coffee.svg",
    translation: "/assets/icons/translation.svg",
    location: "/assets/icons/location.svg",
    tag: "/assets/icons/tag.svg",
    heart: "/assets/icons/heart.svg",
    calendar: "/assets/icons/calendar.svg",
    activity_1: "/assets/icons/activity_1.svg",
    activity_2: "/assets/icons/activity_2.svg",
    activity_3: "/assets/icons/activity_3.svg",
  },
  images: {
    logo: "/assets/icons/logo.svg",
    cover_bg: "/images/cover_background.png",
    contact_location: "/images/contact_location.png",
    cover_bg_complete: "/images/cover_background_complete.png",
  },
};
